create table public.items (
  id bigint generated by default as identity not null,
  part_id text not null,
  description text null,
  created_at timestamp with time zone not null default now(),
  constraint items_pkey primary key (id),
  constraint items_part_id_key unique (part_id)
) TABLESPACE pg_default;